### ISSUE TITLE
Prompting for HTTPS credentials with Gitlab?

### ISSUE THREAD

**Issue by Xiol** [Masterminds/glide-report#2]
Hi,

We use Gitlab internally and some of our projects have dependencies which are pulled in from there. Glide Report seems to want to access those repositories via HTTPS rather than SSH, resulting in a login prompt. Projects with multiple dependencies have the username/password prompts all outputted at the same time:

```
[INFO]  glide.lock not found, attempting to generate. This may take a moment...
Username for 'https://gitlab': Username for 'https://gitlab.acme.com: Username for 'https://gitlab.acme.com': Username for 'https://gitlab.acme.com': Username for 'https://gitlab.acme.com': Username for 'https://gitlab.acme.com':
```

We're using Godep, and as far as I can tell there is no reference to HTTPS repositories in dependencies list.

**Comment by mattfarina** [comment]
@Xiol Unless other information is supplied Glide Report doesn't know how else to access aside from anonymous `https://` access.

With Glide you can specify an alternative locations. For example, in the `glide.yaml` file you can have:

``` yaml
- package: gitlab.acme.com/foo/bar
  repo: git@gitlab.acme.com:foo/bar.git
```

Glide and the report will clone using those creds instead. This works for private access, forks, etc.
